#!/bin/bash

# CRY-A-4MCP Generated Setup Script
# Generated by Setup Wizard

set -e

echo 'Starting CRY-A-4MCP setup...'

# Start Docker services
echo 'Starting Docker services...'
docker compose -f docker-stack/docker-compose.yml -f docker-compose.override.yml up -d --build --remove-orphans

# Wait for services to be ready
echo 'Waiting for services to start...'
sleep 30

# Run health check
echo 'Running health check...'
./scripts/health_check.sh

echo 'Setup complete!'
echo 'Access your services at:'
echo '  - Qdrant: http://localhost:6333'
echo '  - Neo4j: http://localhost:7474'
echo '  - Grafana: http://localhost:3000'
echo '  - MCP Server: http://localhost:8000'