name: Comprehensive API Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-asyncio pytest-json-report
        pip install httpx fastapi uvicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi
    
    - name: Create test database
      run: |
        # Create a temporary SQLite database for testing
        mkdir -p test_data
        touch test_data/test.db
    
    - name: Run linting (if available)
      run: |
        # Install and run linting tools if they exist
        pip install ruff black || true
        if command -v ruff &> /dev/null; then
          echo "Running ruff linting..."
          ruff check src/ || echo "Ruff linting completed with warnings"
        fi
        if command -v black &> /dev/null; then
          echo "Running black formatting check..."
          black --check src/ || echo "Black formatting check completed with warnings"
        fi
    
    - name: Run URL Configurations CRUD Tests
      run: |
        python -m pytest tests/api/test_url_configurations_crud.py -v --tb=short --cov=src --cov-report=xml:coverage-url-configs.xml
      continue-on-error: true
    
    - name: Run URL Mappings CRUD Tests
      run: |
        python -m pytest tests/api/test_url_mappings_crud.py -v --tb=short --cov=src --cov-report=xml:coverage-url-mappings.xml
      continue-on-error: true
    
    - name: Run Extractors CRUD Tests
      run: |
        python -m pytest tests/api/test_extractors_crud.py -v --tb=short --cov=src --cov-report=xml:coverage-extractors.xml
      continue-on-error: true
    
    - name: Run Crawlers CRUD Tests
      run: |
        python -m pytest tests/api/test_crawlers_crud.py -v --tb=short --cov=src --cov-report=xml:coverage-crawlers.xml
      continue-on-error: true
    
    - name: Run OpenRouter API Tests
      run: |
        python -m pytest tests/api/test_openrouter_crud.py -v --tb=short --cov=src --cov-report=xml:coverage-openrouter.xml
      continue-on-error: true
    
    - name: Run Integration Tests
      run: |
        python -m pytest tests/integration/test_end_to_end_workflows.py -v --tb=short --cov=src --cov-report=xml:coverage-integration.xml
      continue-on-error: true
    
    - name: Run All Existing Tests
      run: |
        python -m pytest tests/ -v --tb=short --cov=src --cov-report=xml:coverage-all.xml --cov-report=html:htmlcov
      continue-on-error: true
    
    - name: Run Comprehensive Test Suite
      run: |
        python run_tests.py
      continue-on-error: true
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage-*.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          test_report.txt
          htmlcov/
          coverage-*.xml
    
    - name: Upload test report as comment (on PR)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          try {
            const report = fs.readFileSync('test_report.txt', 'utf8');
            const body = `## 🧪 Test Report for Python ${{ matrix.python-version }}\n\n\`\`\`\n${report}\n\`\`\``;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
          } catch (error) {
            console.log('Could not read test report:', error.message);
          }

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install security scanning tools
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
    
    - name: Run safety check
      run: |
        if [ -f requirements.txt ]; then
          safety check -r requirements.txt || echo "Safety check completed with warnings"
        else
          echo "No requirements.txt found, skipping safety check"
        fi
    
    - name: Run bandit security scan
      run: |
        bandit -r src/ -f json -o bandit-report.json || echo "Bandit scan completed with warnings"
        bandit -r src/ || echo "Bandit scan completed with warnings"
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-scan-results
        path: bandit-report.json

  performance-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-benchmark httpx fastapi uvicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi
    
    - name: Run performance tests
      run: |
        # Run a subset of tests with performance benchmarking
        python -m pytest tests/integration/test_end_to_end_workflows.py::TestSystemIntegration::test_performance_under_load -v --benchmark-only --benchmark-json=benchmark.json || echo "Performance tests completed"
    
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: performance-results
        path: benchmark.json

  notify-status:
    runs-on: ubuntu-latest
    needs: [test, security-scan, performance-test]
    if: always()
    steps:
    - name: Notify test completion
      run: |
        echo "🎯 Test pipeline completed!"
        echo "📊 Test job status: ${{ needs.test.result }}"
        echo "🔒 Security scan status: ${{ needs.security-scan.result }}"
        echo "⚡ Performance test status: ${{ needs.performance-test.result }}"
        
        if [ "${{ needs.test.result }}" = "success" ]; then
          echo "✅ All tests passed! Safe to merge."
        else
          echo "❌ Some tests failed. Please review before merging."
        fi